services:
  - type: web
    name: real-estate-ai-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port --reload main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0